### ISSUE TITLE
shared

### ISSUE THREAD

**Issue by mattunlv** [mattunlv/ProcessJ#15]
void f(shared chan<int>.write out) {
  out.write(0);
}

void g(chan<int>.read in) {
  int x;
  x = in.read();
}

public void main(string args[]) {
  shared chan<int> c;
  par {
    f(c.write);
    g(c.read);
  }
}

crashes the compiler, and when putting shared on the reading end in g this happens:

Exception in thread "main" java.lang.IllegalArgumentException: no such attribute: type
	at org.stringtemplate.v4.ST.add(ST.java:223)
	at codegen.java.CodeGenJava.createChannelReadExpr(CodeGenJava.java:2408)
	at codegen.java.CodeGenJava.visitAssignment(CodeGenJava.java:763)
	at ast.Assignment.visit(Assignment.java:50)
	at codegen.java.CodeGenJava.visitExprStat(CodeGenJava.java:892)
	at ast.ExprStat.visit(ExprStat.java:17)
	at codegen.java.CodeGenJava.visitSequence(CodeGenJava.java:1191)
	at ast.Sequence.visit(Sequence.java:58)
	at codegen.java.CodeGenJava.visitBlock(CodeGenJava.java:1176)
	at ast.Block.visit(Block.java:22)
	at codegen.java.CodeGenJava.visitProcTypeDecl(CodeGenJava.java:371)
	at ast.ProcTypeDecl.visit(ProcTypeDecl.java:64)
	at codegen.java.CodeGenJava.visitCompilation(CodeGenJava.java:275)
	at ast.Compilation.visit(Compilation.java:41)
	at ProcessJc.generateCodeJava(ProcessJc.java:431)
	at ProcessJc.main(ProcessJc.java:392)
-- Setting absolute path, file and package name for 'shared.pj'.

**Comment by clcuenca** [comment]
I've created an issue for this that corresponds with an end-to-end test. I'll be closing this one in favor of the most recent one to track it while establishing the regression tests.
